### ISSUE TITLE
Cannot retrieve saved Turbo Warp project

### ISSUE THREAD

**Issue by mandyx4z** [TurboWarp/sb3fix#26]
My son cannot retrieve his Turbo Warp project. He saved it as he usually does but it shows 0kb.

Good Program 1.sb3
ERROR: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
Error: End of data reached (data length = 0, asked index = 4). Corrupted zip ?
    at a.checkIndex (https://turbowarp.github.io/sb3fix/sb3fix.js:2:18735)
    at a.checkOffset (https://turbowarp.github.io/sb3fix/sb3fix.js:2:18648)
    at a.readData (https://turbowarp.github.io/sb3fix/sb3fix.js:2:20465)
    at a.readString (https://turbowarp.github.io/sb3fix/sb3fix.js:2:19154)
    at h.isSignature (https://turbowarp.github.io/sb3fix/sb3fix.js:2:36417)
    at h.readEndOfCentral (https://turbowarp.github.io/sb3fix/sb3fix.js:2:38662)
    at h.load (https://turbowarp.github.io/sb3fix/sb3fix.js:2:40409)
    at https://turbowarp.github.io/sb3fix/sb3fix.js:2:11349
    at async Object.fixZip (https://turbowarp.github.io/sb3fix/sb3fix.js:2:102887)
    at async processFile (https://turbowarp.github.io/sb3fix/:193:25)

Any assistance would be appreciated.

**Comment by GarboMuffin** [comment]
please check file > restore points, we can't recover a file if there is no data in it
